default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Deploy to AppCenter"
  lane :deployAppCenter do
    gradle(
      task: "clean assembleRelease"
    )

    api_token = ENV["APPCENTER_API_TOKEN"]
    owner_name = ENV["APPCENTER_OWNER_NAME"]
    app_name = ENV["APPCENTER_APP_NAME"]
    ## You can use the following line to provide a default value if the environment variable doesn't exist
    # app_name ||= "appcenter-sampleapp-android"

    appcenter_upload(
      api_token: api_token,
      owner_name: owner_name,
      owner_type: "organization", # Default is user - set to organization for appcenter organizations
      destinations: "*", # Default is 'Collaborators', use '*' for all distribution groups
      app_name: app_name,
      file: Actions.lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH],
      mapping: Actions.lane_context[SharedValues::GRADLE_MAPPING_TXT_OUTPUT_PATH],
      notify_testers: false # Set to false if you don't want to notify testers of your new release or true if you do (default: `false`)
    )
  end
end
